// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ride.Infrastructure.Persistence;

#nullable disable

namespace Ride.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RideDbContext))]
    [Migration("20260208232816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ride.Domain.Entities.RideEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoConfirmBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer")
                        .HasColumnName("AvailableSeats");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("DriverId");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasColumnName("TotalSeats");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartureTime")
                        .HasDatabaseName("IX_Rides_DepartureTime");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("IX_Rides_DriverId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Rides_Status");

                    b.ToTable("Rides", (string)null);
                });

            modelBuilder.Entity("Ride.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "RetryCount")
                        .HasDatabaseName("IX_OutboxMessages_ProcessedAt_RetryCount");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Ride.Domain.Entities.RideEntity", b =>
                {
                    b.OwnsOne("Ride.Domain.ValueObjects.Location", "Destination", b1 =>
                        {
                            b1.Property<Guid>("RideEntityId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("DestinationLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("DestinationLongitude");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("DestinationName");

                            b1.HasKey("RideEntityId");

                            b1.ToTable("Rides");

                            b1.WithOwner()
                                .HasForeignKey("RideEntityId");
                        });

                    b.OwnsOne("Ride.Domain.ValueObjects.Location", "Origin", b1 =>
                        {
                            b1.Property<Guid>("RideEntityId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("OriginLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("OriginLongitude");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("OriginName");

                            b1.HasKey("RideEntityId");

                            b1.ToTable("Rides");

                            b1.WithOwner()
                                .HasForeignKey("RideEntityId");
                        });

                    b.OwnsOne("Ride.Domain.ValueObjects.Money", "PricePerSeat", b1 =>
                        {
                            b1.Property<Guid>("RideEntityId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PricePerSeat");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("RideEntityId");

                            b1.ToTable("Rides");

                            b1.WithOwner()
                                .HasForeignKey("RideEntityId");
                        });

                    b.Navigation("Destination")
                        .IsRequired();

                    b.Navigation("Origin")
                        .IsRequired();

                    b.Navigation("PricePerSeat")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
